name: CloudType Monitor

on:
  schedule:
    - cron: '0,10,20,30 20 * * *'  # UTC 20:00, 20:10, 20:20, 20:30 (한국시간 5:00, 5:10, 5:20, 5:30)
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Run monitor script
        env:
          CLOUDTYPE_ID: ${{ secrets.CLOUDTYPE_ID }}
          CLOUDTYPE_PW: ${{ secrets.CLOUDTYPE_PW }}
        run: python main.py

      - name: Upload logs (if any)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: monitor-logs
          path: |
            *.log
            *.png